use anyhow::{anyhow, Context, Result};
use serde_json::{json, Value};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResolutionStrategy {
    KeepOurs,
    KeepTheirs,
    SmartBlend,
}

#[derive(Debug, Clone)]
pub struct AiSuggestion {
    pub title: String,
    pub explanation: String,
    pub resolved_text: String,
}

#[derive(Debug, Default)]
pub struct LocalConflictAgent;

#[derive(Debug, Clone)]
pub struct OpenAiConfig {
    pub base_url: String,
    pub model: String,
    pub api_key: String,
}

#[derive(Debug, Default)]
pub struct RemoteOpenAiAgent;

impl LocalConflictAgent {
    pub fn suggest(&self, source: &str, strategy: ResolutionStrategy) -> AiSuggestion {
        let resolved_text = resolve_markers(source, strategy);
        let (title, explanation) = match strategy {
            ResolutionStrategy::KeepOurs => (
                "Use Current Branch".to_owned(),
                "Keeps local branch chunks in each conflict block and drops incoming chunks."
                    .to_owned(),
            ),
            ResolutionStrategy::KeepTheirs => (
                "Use Incoming Branch".to_owned(),
                "Takes incoming branch chunks in each conflict block and drops local chunks."
                    .to_owned(),
            ),
            ResolutionStrategy::SmartBlend => (
                "Blend Changes".to_owned(),
                "Combines both sides and de-duplicates exact duplicate lines. Useful default when both sides add valid code.".to_owned(),
            ),
        };

        AiSuggestion {
            title,
            explanation,
            resolved_text,
        }
    }
}

impl RemoteOpenAiAgent {
    pub fn suggest(
        &self,
        source: &str,
        strategy: ResolutionStrategy,
        ours_label: &str,
        theirs_label: &str,
        config: &OpenAiConfig,
    ) -> Result<AiSuggestion> {
        if config.api_key.trim().is_empty() {
            return Err(anyhow!("OpenAI API key is empty"));
        }

        let endpoint = format!("{}/chat/completions", config.base_url.trim_end_matches('/'));

        let system_prompt = "You resolve git conflict markers. Return only the resolved file content. Never include markdown code fences. Preserve formatting and syntax for the file language.";

        let user_prompt = format!(
            "Strategy: {}\nCurrent branch label: {}\nIncoming branch label: {}\n\nResolve the conflict markers in this file content:\n\n{}",
            strategy_name(strategy),
            ours_label,
            theirs_label,
            source,
        );

        let body = json!({
            "model": config.model,
            "temperature": 0.0,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ]
        });

        let response: Value = ureq::AgentBuilder::new()
            .build()
            .post(&endpoint)
            .set("Authorization", &format!("Bearer {}", config.api_key))
            .set("Content-Type", "application/json")
            .send_json(body)
            .context("failed request to OpenAI endpoint")?
            .into_json()
            .context("failed to parse OpenAI response as JSON")?;

        let content = extract_chat_completion_content(&response)
            .ok_or_else(|| anyhow!("OpenAI response missing choices[0].message.content"))?;

        let cleaned = strip_code_fences(content).trim().to_owned();
        if cleaned.is_empty() {
            return Err(anyhow!("OpenAI returned empty resolution text"));
        }

        Ok(AiSuggestion {
            title: format!("OpenAI Suggestion ({})", strategy_name(strategy)),
            explanation: "Generated by remote model with conflict-aware instructions.".to_owned(),
            resolved_text: ensure_newline_parity(source, &cleaned),
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ParseState {
    Normal,
    Ours,
    Theirs,
}

pub fn resolve_markers(source: &str, strategy: ResolutionStrategy) -> String {
    let mut output: Vec<String> = Vec::new();
    let mut ours: Vec<String> = Vec::new();
    let mut theirs: Vec<String> = Vec::new();
    let mut state = ParseState::Normal;

    for line in source.lines() {
        if line.starts_with("<<<<<<<") {
            state = ParseState::Ours;
            ours.clear();
            theirs.clear();
            continue;
        }

        if line.starts_with("=======") && state == ParseState::Ours {
            state = ParseState::Theirs;
            continue;
        }

        if line.starts_with(">>>>>>>") && state == ParseState::Theirs {
            let selected = select_block(&ours, &theirs, strategy);
            output.extend(selected);
            state = ParseState::Normal;
            continue;
        }

        match state {
            ParseState::Normal => output.push(line.to_owned()),
            ParseState::Ours => ours.push(line.to_owned()),
            ParseState::Theirs => theirs.push(line.to_owned()),
        }
    }

    if state != ParseState::Normal {
        output.push("// Warning: unresolved conflict marker tail preserved".to_owned());
        output.extend(ours);
        output.extend(theirs);
    }

    let mut resolved = output.join("\n");
    if source.ends_with('\n') {
        resolved.push('\n');
    }
    resolved
}

fn select_block(ours: &[String], theirs: &[String], strategy: ResolutionStrategy) -> Vec<String> {
    match strategy {
        ResolutionStrategy::KeepOurs => ours.to_vec(),
        ResolutionStrategy::KeepTheirs => theirs.to_vec(),
        ResolutionStrategy::SmartBlend => {
            let mut merged = Vec::with_capacity(ours.len() + theirs.len());
            for line in ours {
                if !merged.contains(line) {
                    merged.push(line.clone());
                }
            }
            for line in theirs {
                if !merged.contains(line) {
                    merged.push(line.clone());
                }
            }
            merged
        }
    }
}

fn strategy_name(strategy: ResolutionStrategy) -> &'static str {
    match strategy {
        ResolutionStrategy::KeepOurs => "keep-ours",
        ResolutionStrategy::KeepTheirs => "keep-theirs",
        ResolutionStrategy::SmartBlend => "smart-blend",
    }
}

fn extract_chat_completion_content(response: &Value) -> Option<&str> {
    response
        .get("choices")?
        .as_array()?
        .first()?
        .get("message")?
        .get("content")?
        .as_str()
}

fn strip_code_fences(input: &str) -> &str {
    let trimmed = input.trim();
    if !trimmed.starts_with("```") {
        return trimmed;
    }

    let without_first = trimmed
        .find('\n')
        .and_then(|idx| trimmed.get((idx + 1)..))
        .unwrap_or(trimmed);

    if let Some(last) = without_first.rfind("```") {
        without_first.get(..last).unwrap_or(without_first).trim()
    } else {
        without_first.trim()
    }
}

fn ensure_newline_parity(source: &str, output: &str) -> String {
    let mut out = output.to_owned();
    if source.ends_with('\n') && !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::{resolve_markers, strip_code_fences, ResolutionStrategy};

    #[test]
    fn keep_ours_strategy() {
        let input = "a\n<<<<<<< HEAD\nours\n=======\ntheirs\n>>>>>>> main\nb\n";
        let output = resolve_markers(input, ResolutionStrategy::KeepOurs);
        assert_eq!(output, "a\nours\nb\n");
    }

    #[test]
    fn keep_theirs_strategy() {
        let input = "<<<<<<< HEAD\nours\n=======\ntheirs\n>>>>>>> main\n";
        let output = resolve_markers(input, ResolutionStrategy::KeepTheirs);
        assert_eq!(output, "theirs\n");
    }

    #[test]
    fn smart_blend_dedupes() {
        let input = "<<<<<<< HEAD\nline\nshared\n=======\nshared\nline2\n>>>>>>> main\n";
        let output = resolve_markers(input, ResolutionStrategy::SmartBlend);
        assert_eq!(output, "line\nshared\nline2\n");
    }

    #[test]
    fn strip_fences_keeps_inner_content() {
        let input = "```rust\nlet x = 1;\n```";
        assert_eq!(strip_code_fences(input), "let x = 1;");
    }
}
